# Generated by Django 4.0.3 on 2022-03-13 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stuck',
            field=models.IntegerField(verbose_name='재고'),
        ),
    ]
